/* Auto-generated by: https://github.com/pmndrs/gltfjsx */
import * as THREE from 'three'
import React, { useEffect } from 'react' // useEffect hinzugefügt
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF, SkeletonUtils } from 'three-stdlib'

type ActionName = 'Idle_15' | 'Idle_3' | 'Idle_9' | 'Regular_Jump' | 'Running' | 'Standard_Forward_Charge_inplace' | 'cc' | 'Walking' | 'walking_2_inplace'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    char1: THREE.SkinnedMesh
    Hips: THREE.Bone
  }
  materials: {
    Material_1: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: any) {
  const group = React.useRef<THREE.Group>(null) // null initialisiert für TS
  const { scene, animations } = useGLTF('/models/player.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone) as any
  const { actions } = useAnimations(animations, group)

  // NEU: Wir zwingen alle Animationen in einen unendlichen Loop!
  useEffect(() => {
    Object.values(actions).forEach((action) => {
      if (action) {
        action.setLoop(THREE.LoopRepeat, Infinity);
      }
    });
  }, [actions]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" scale={0.01}>
          <primitive object={nodes.Hips} />
        </group>
        <skinnedMesh name="char1" geometry={nodes.char1.geometry} material={materials.Material_1} skeleton={nodes.char1.skeleton} scale={0.01} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/player.glb')