import type { BuildingData } from "./town-types";

export const BANK_BUILDING_ID = "26";
export const ARENA_BUILDING_ID = "21";
export const CASINO_BUILDING_ID = "24";
export const STOCK_EXCHANGE_BUILDING_ID = "25";

export const HARDCODED_BUILDINGS: BuildingData[] = [
  {
    id: "8",
        position: [-5.5, 1.1, 4.6],
    rotationX: -70,
    rotationY: 0,
    iconPosition: 0.54,
    name: "1001 Nights",
    image: "https://www.boozedbunnytown.com/media/buildings/1001_nights.webp",
        spriteConfig: {
  "fps": 24,
  "rows": 5,
  "columns": 4,
  "totalFrames": 20
    },
    type: "Commercial",
    color: "#BD00FF",
    scale: 4.3,
  },
  {
    id: "9",
    position: [-2.0, 1.3, -2.5],
    rotationX: -70,
    rotationY: 0,
    scale: 5.5,
    iconPosition: 0.55,
    name: "Akihabara",
    image: "https://www.boozedbunnytown.com/media/buildings/akihabara.webp",
    spriteConfig: {
      columns: 4,
      rows: 12,
      totalFrames: 36,
      fps: 12,
    },
    type: "Commercial",
    color: "#BD00FF",
  },
  {
    id: "10",
    position: [-15.3, 0.8, 1.6],
    rotationX: -70,
    rotationY: 0,
    scale: 4.5,
    iconPosition: 0.44,
    name: "Boat House",
    image: "https://www.boozedbunnytown.com/media/buildings/boat_house.webp",
    type: "Commercial",
    color: "#BD00FF",
  },
  {
    id: "11",
    position: [-12.6, 0.8, -1],
    rotationX: -70,
    rotationY: 0,
    scale: 4.5,
    iconPosition: 0.44,
    name: "Dune Partyhouse",
    image:
      "https://www.boozedbunnytown.com/media/buildings/dune_partyhouse.webp",
    type: "Commercial",
    color: "#BD00FF",
  },
  {
    id: "12",
    position: [14.8, 0.8, 2.3],
    rotationX: -70,
    rotationY: 0,
    scale: 3.7,
    iconPosition: 0.44,
    name: "Feet House",
    image: "https://www.boozedbunnytown.com/media/buildings/feet_house.webp",
    type: "Commercial",
    color: "#BD00FF",
  },
  {
    id: "13",
    position: [-10.5, 1.2, 3],
    rotationX: -70,
    rotationY: 0,
    scale: 7,
    iconPosition: 0.5,
    name: "Holy Rave",
    image: "https://www.boozedbunnytown.com/media/buildings/holy_rave.webp",
    type: "Commercial",
    color: "#BD00FF",
  },
  {
    id: "14",
      position: [-1.2, 0.9, 1.5],
    rotationX: -70,
    rotationY: 0,
    scale: 5.5,
    iconPosition: 0.5,
    name: "Hoppy Heaven",
    image: "https://www.boozedbunnytown.com/media/buildings/hoppy_heaven.webp",
    type: "Commercial",
    color: "#BD00FF",
  },
  {
    id: "15",
    position: [6.8, 0.8, 3.5],
    rotationX: -70,
    rotationY: 0,
    scale: 4.5,
    iconPosition: 0.4,
    name: "Pipe House",
    image: "https://www.boozedbunnytown.com/media/buildings/pipe_house.webp",
    spriteConfig: {
      columns: 4,
      rows: 6,
      totalFrames: 20,
      fps: 12,
    },
    type: "Commercial",
    color: "#BD00FF",
  },
  {
    id: "16",
    position: [6, 5, -7],
    rotationX: -70,
    scale: 2.5,
    iconPosition: 0.64,
    name: "Up Up Balloon",
    image: "https://www.boozedbunnytown.com/media/buildings/up_up_balloon.webp",
    spriteConfig: {
      columns: 4,
      rows: 12,
      totalFrames: 48,
      fps: 24,
    },
    type: "Commercial",
    color: "#BD00FF",
  },
  {
    id: "17",
    position: [2.1, 0.7, 0.6],
    rotationX: -70,
    rotationY: 0,
    scale: 3.5,
    iconPosition: 0.5,
    name: "Up Up House",
    image: "https://www.boozedbunnytown.com/media/buildings/up_up_house.webp",
    type: "Commercial",
    color: "#BD00FF",
  },
  {
    id: "18",
    position: [11.8, 0.8, 0.2],
    rotationX: -70,
    rotationY: 0,
    scale: 5,
    iconPosition: 0.64,
    name: "Vino Vibes",
    image: "https://www.boozedbunnytown.com/media/buildings/vino_vibes.webp",
    type: "Commercial",
    color: "#BD00FF",
  },
  {
    id: "19",
    position: [3.3, 1.2, -3],
    rotationX: -70,
    rotationY: 0,
    scale: 6,
    iconPosition: 0.5,
    name: "Vodka Palace",
    image: "https://www.boozedbunnytown.com/media/buildings/vodka_palace.webp",
    spriteConfig: {
      columns: 4,
      rows: 5,
      totalFrames: 20,
      fps: 12,
    },
    type: "Commercial",
    color: "#BD00FF",
  },
  {
    id: "20",
    position: [-5.8, 1, 0.5],
    rotationX: -70,
    rotationY: 0,
    scale: 6,
    iconPosition: 0.56,
    name: "Vulcan Temple",
    image: "https://www.boozedbunnytown.com/media/buildings/vulcan_temple.webp",
    spriteConfig: {
      columns: 4,
      rows: 12,
      totalFrames: 48,
      fps: 6,
    },
    type: "Commercial",
    color: "#BD00FF",
  },
  {
    id: "21",
    position: [0.5, 1.4, 6],
    rotationX: -70,
    scale: 8.5,
    iconPosition: 0.05,
    name: "Arena",
    image: "https://www.boozedbunnytown.com/media/buildings/arena.webp",
    spriteConfig: {
      columns: 4,
      rows: 8,
      totalFrames: 30,
      fps: 12,
    },
    type: "Commercial",
    color: "#BD00FF",
  },
  {
    id: "22",
    position: [-8.6, 0.7, -1.4],
    rotationX: -70,
    rotationY: 0,
    scale: 3.9,
    iconPosition: 0.6,
    name: "Love Palace",
    image: "https://www.boozedbunnytown.com/media/buildings/love_palace.webp",
    spriteConfig: {
      columns: 4,
      rows: 5,
      totalFrames: 20,
      fps: 12,
    },
    type: "Commercial",
    color: "#BD00FF",
  },
  {
    id: "23",
    position: [3.2, 0.8, 2.4],
    rotationX: -70,
    rotationY: 0,
    scale: 3.4,
    iconPosition: 0.58,
    name: "Gnome Party House",
    image:
      "https://www.boozedbunnytown.com/media/buildings/gnome_party_house.webp",
    type: "Commercial",
    color: "#BD00FF",
  },
  {
    id: "24",
    position: [6.5, 1.2, -0.8],
    rotationX: -70,
    rotationY: 0,
    scale: 6.8,
    iconPosition: 0.34,
    name: "Casino Pyramid",
    image:
      "https://www.boozedbunnytown.com/media/buildings/casino_pyramid.webp",
    spriteConfig: {
      columns: 4,
      rows: 5,
      totalFrames: 20,
      fps: 12,
    },
    type: "Commercial",
    color: "#BD00FF",
  },
  {
    id: "25",
    position: [9.3, 1, -2.8],
    rotationX: -70,
    rotationY: 0,
    scale: 5,
    iconPosition: 0.54,
    name: "Stock Exchange",
    image: "https://www.boozedbunnytown.com/media/buildings/stock.webp",
    type: "Commercial",
    color: "#BD00FF",
  },
  {
    id: "26",
    position: [14, 0.9, -2.4],
    rotationX: -70,
    rotationY: 0,
    scale: 4.5,
    iconPosition: 0.54,
    name: "BBTown Bank",
    image: "https://www.boozedbunnytown.com/media/buildings/bank.webp",
    type: "Commercial",
    color: "#BD00FF",
  },
  {
    id: "27",
    position: [10.7, 0.9, 4.6],
    rotationX: -70,
    rotationY: 0,
    scale: 5,
    iconPosition: 0.54,
    name: "WhimsicLe's House",
    image: "https://www.boozedbunnytown.com/media/buildings/barbys_house.webp",
    type: "Commercial",
    color: "#BD00FF",
  },
];
