import type { BuildingData } from "./town-types";

export const BANK_BUILDING_ID = "4";
export const ARENA_BUILDING_ID = "21";

export const HARDCODED_BUILDINGS: BuildingData[] = [
  {
    id: "1",
    position: [-1.00, 0.90, -0.57],
    rotationY: 80,
    glb: "https://www.boozedbunnytown.com/media/models/rustic_stein.glb",
    type: "Town Hall",
    color: "#BD00FF",
  },
  {
    id: "2",
    position: [-1.12, 0.90, -5.49],
    rotationY: -142,
    glb: "https://www.boozedbunnytown.com/media/models/barbys_house.glb",
    type: "Residential",
    color: "#FFB800",
  },
  {
    id: "3",
    position: [-2.71, 0.90, 1.68],
    rotationY: 98,
    glb: "https://www.boozedbunnytown.com/media/models/bb_house_fin.glb",
    type: "Industrial",
    color: "#FF4D00",
  },
  {
    id: "4",
    position: [-3.30, 0.90, -1.35],
    rotationY: 47,
    glb: "https://www.boozedbunnytown.com/media/models/clocktower_fin.glb",
    type: "Commercial",
    color: "#BD00FF",
  },
  {
    id: "5",
    position: [6.06, 0.90, -2.02],
    rotationY: -40,
    glb: "https://www.boozedbunnytown.com/media/models/massage_saloon.glb",
    type: "Commercial",
    color: "#BD00FF",
  },
  {
    id: "6",
    position: [7.80, 0.90, 2.00],
    rotationY: 80,
    glb: "https://www.boozedbunnytown.com/media/models/tower.glb",
    type: "Commercial",
    color: "#BD00FF",
  },
  {
    id: "7",
    position: [-5.33, 0.97, -4.20],
    rotationY: 50,
    glb: "https://www.boozedbunnytown.com/media/models/bb_gogo_bar.glb",
    type: "Commercial",
    color: "#BD00FF",
  },
  {
    id: "8",
    position: [1.07, 0.97, 5.75],
    rotationY: 147,
    glb: "https://www.boozedbunnytown.com/media/models/1001_nights.glb",
    type: "Commercial",
    color: "#BD00FF",
  },
  {
    id: "9",
    position: [-2.65, 0.97, -7.43],
    rotationY: 50,
    glb: "https://www.boozedbunnytown.com/media/models/akihabara.glb",
    type: "Commercial",
    color: "#BD00FF",
  },
  {
    id: "10",
    position: [1.56, 0.97, -9.05],
    rotationY: 88,
    glb: "https://www.boozedbunnytown.com/media/models/boat_house.glb",
    type: "Commercial",
    color: "#BD00FF",
  },
  {
    id: "11",
    position: [7.80, 0.97, -0.30],
    rotationY: 13,
    glb: "https://www.boozedbunnytown.com/media/models/dune_partyhouse.glb",
    type: "Commercial",
    color: "#BD00FF",
  },
  {
    id: "12",
    position: [-0.00, 0.97, -5.21],
    rotationY: 50,
    glb: "https://www.boozedbunnytown.com/media/models/feet_house.glb",
    type: "Commercial",
    color: "#BD00FF",
  },
  {
    id: "13",
    position: [-8.01, 0.97, -0.99],
    rotationY: 50,
    glb: "https://www.boozedbunnytown.com/media/models/holy_rave.glb",
    type: "Commercial",
    color: "#BD00FF",
  },
  {
    id: "14",
    position: [9.51, 0.97, -5.98],
    rotationY: 26,
    glb: "https://www.boozedbunnytown.com/media/models/hoppy_heaven.glb",
    type: "Commercial",
    color: "#BD00FF",
  },
  {
    id: "15",
    position: [-11.45, 0.97, -5.20],
    rotationY: 28,
    glb: "https://www.boozedbunnytown.com/media/models/pipe_house.glb",
    type: "Commercial",
    color: "#BD00FF",
  },
  {
    id: "16",
    position: [-2.4, 2.67, 4.0],
    rotationY: 105,
    glb: "https://www.boozedbunnytown.com/media/models/up_up_balloon.glb",
    type: "Commercial",
    color: "#BD00FF",
  },
  {
    id: "17",
    position: [-0.59, 0.97, 3.69],
    rotationY: 125,
    glb: "https://www.boozedbunnytown.com/media/models/up_up_house.glb",
    type: "Commercial",
    color: "#BD00FF",
  },
  {
    id: "18",
    position: [9.79, 0.97, -1.91],
    rotationY: 24,
    glb: "https://www.boozedbunnytown.com/media/models/vino_vibes.glb",
    type: "Commercial",
    color: "#BD00FF",
  },
  {
    id: "19",
    position: [4.27, 0.97, -5.56],
    rotationY: 50,
    glb: "https://www.boozedbunnytown.com/media/models/vodka_palace.glb",
    type: "Commercial",
    color: "#BD00FF",
  },
  {
    id: "20",
    position: [3.21, 0.97, 0.92],
    rotationY: 41,
    glb: "https://www.boozedbunnytown.com/media/models/vulcan_temple.glb",
    type: "Commercial",
    color: "#BD00FF",
  },
  {
    id: "21",
    position: [1.72, 1, -2.16],
    rotationY: 0,
    glb: "https://www.boozedbunnytown.com/media/models/arena-v2.glb",
    type: "Commercial",
    color: "#BD00FF",
    scale: 2,
  },
];
