import type { BuildingData } from "./town-types";

export const BANK_BUILDING_ID = "4";
export const ARENA_BUILDING_ID = "21";

export const HARDCODED_BUILDINGS: BuildingData[] = [
/*   {
    id: "1",
    position: [-11.02, 0.9, 1.03],
    rotationY: 80,
    image: "https://www.boozedbunnytown.com/media/buildings/vino_vibes.webp",
    type: "Town Hall",
    color: "#BD00FF",
  },
  {
    id: "2",
    position: [-1.12, 0.9, -5.49],
    rotationY: -142,
    image: "https://www.boozedbunnytown.com/media/buildings/barbys_house.webp",
    type: "Residential",
    color: "#FFB800",
  },
  {
    id: "3",
    position: [-7.6, 0.9, 3],
    rotationY: 98,
    image: "https://www.boozedbunnytown.com/media/buildings/vino_vibes.webp",
    type: "Industrial",
    color: "#FF4D00",
  }, */
/*   {
    id: "4",
    position: [-3.3, 0.9, -1.35],
    rotationY: 47,
    image: "https://www.boozedbunnytown.com/media/buildings/vino_vibes.webp",
    type: "Commercial",
    color: "#BD00FF",
  },
  {
    id: "5",
    position: [-0.58, 0.9, -7.72],
    rotationY: -40,
    image: "https://www.boozedbunnytown.com/media/buildings/vino_vibes.webp",
    type: "Commercial",
    color: "#BD00FF",
  }, */
 /*  {
    id: "6",
    position: [-5.29, 0.9, -7.29],
    rotationY: 80,
    image: "https://www.boozedbunnytown.com/media/buildings/vino_vibes.webp",
    type: "Commercial",
    color: "#BD00FF",
  },
  {
    id: "7",
    position: [-2, 1.8, -3],
    rotationX: -70,
    rotationY: 10,
    scale: 5.5,
    iconPosition: 0.44,
    image: "https://www.boozedbunnytown.com/media/buildings/bb_gogo_bar.webp",
    type: "Commercial",
    color: "#BD00FF",
  }, */
  {
    id: "8",
    position: [5.8, 1.50, 0.8],
    rotationX: -70,
       rotationY: -10,
        iconPosition: 0.54,
    name: "1001 Nights",
    image: "https://www.boozedbunnytown.com/media/buildings/1001_nights.webp",
    type: "Commercial",
    color: "#BD00FF",
    scale: 3.5,
  },
  {
    id: "9",
    position: [-2, 1.8, -3],
    rotationX: -70,
    rotationY: 10,
    scale: 5.5,
    iconPosition: 0.55,
    name: "Akihabara",
    image: "https://www.boozedbunnytown.com/media/buildings/akihabara.webp",
    type: "Commercial",
    color: "#BD00FF",
  },
  {
    id: "10",
    position: [-15.3, 1.8, 2],
    rotationX: -70,
    rotationY: 10,
    scale: 4.5,
    iconPosition: 0.44,
    name: "Boat House",
    image: "https://www.boozedbunnytown.com/media/buildings/boat_house.webp",
    type: "Commercial",
    color: "#BD00FF",
  },
  {
    id: "11",
    position: [-12.6, 1.8, -1],
    rotationX: -70,
    rotationY: 10,
    scale: 4.5,
    iconPosition: 0.44,
    name: "Dune Partyhouse",
    image:
      "https://www.boozedbunnytown.com/media/buildings/dune_partyhouse.webp",
    type: "Commercial",
    color: "#BD00FF",
  },
  {
    id: "12",
    position: [-14.99, 1.80, 5.97],
    rotationX: -70,
    rotationY: 10,
    scale: 4.5,
    iconPosition: 0.44,
    name: "Feet House",
    image: "https://www.boozedbunnytown.com/media/buildings/feet_house.webp",
    type: "Commercial",
    color: "#BD00FF",
  },
  {
    id: "13",
    position: [-11, 1.8, 3],
    rotationX: -70,
    rotationY: 15,
    scale: 7,
    iconPosition: 0.5,
    name: "Holy Rave",
    image: "https://www.boozedbunnytown.com/media/buildings/holy_rave.webp",
    type: "Commercial",
    color: "#BD00FF",
  },
  {
    id: "14",
    position: [8.8, 1.30, 4.3],
    rotationX: -70,
    rotationY: -15,
    scale: 5.5,
    iconPosition: 0.5,
    name: "Hoppy Heaven",
    image: "https://www.boozedbunnytown.com/media/buildings/hoppy_heaven.webp",
    type: "Commercial",
    color: "#BD00FF",
  },
  {
    id: "15",
    position: [9.3, 1.50, .2],
    rotationX: -70,
    rotationY: -15,
    scale: 4.5,
    iconPosition: 0.4,
    name: "Pipe House",
    image: "https://www.boozedbunnytown.com/media/buildings/pipe_house.webp",
    type: "Commercial",
    color: "#BD00FF",
  },
  {
    id: "16",
    position: [6, 1.3, -6.3],
    rotationX: -70,
    scale: 2.5,
    iconPosition: 0.64,
    name: "Up Up Balloon",
    image: "https://www.boozedbunnytown.com/media/buildings/up_up_balloon.webp",
    type: "Commercial",
    color: "#BD00FF",
  },
  {
    id: "17",
    position: [12.6, 1.3, 2.8],
    rotationX: -70,
    rotationY: -15,
    scale: 3.5,
    iconPosition: 0.64,
    name: "Up Up House",
    image: "https://www.boozedbunnytown.com/media/buildings/up_up_house.webp",
    type: "Commercial",
    color: "#BD00FF",
  },
  {
    id: "18",
    position: [12.6, 1.3, -1],
    rotationX: -70,
    rotationY: -15,
    scale: 3.9,
    iconPosition: 0.64,
    name: "Vino Vibes",
    image: "https://www.boozedbunnytown.com/media/buildings/vino_vibes.webp",
    type: "Commercial",
    color: "#BD00FF",
  },
  {
    id: "19",
    position: [3, 1.8, -3],
    rotationX: -70,
    rotationY: -10,
    scale: 5.5,
    iconPosition: 0.58,
    name: "Vodka Palace",
    image: "https://www.boozedbunnytown.com/media/buildings/vodka_palace.webp",
    type: "Commercial",
    color: "#BD00FF",
  },
  {
    id: "20",
    position: [-6, 2.6, 0.4],
   rotationX: -70,
   rotationY: 10,
    scale: 5.5,
        iconPosition: 0.56,
    name: "Vulcan Temple",
    image: "https://www.boozedbunnytown.com/media/buildings/vulcan_temple.webp",
    type: "Commercial",
    color: "#BD00FF",
  },
  {
    id: "21",
    position: [0.5, 2.6, 1],
 rotationX: -70,
    scale: 8.5,
    iconPosition: 0.05,
    name: "Arena V2",
    image: "https://www.boozedbunnytown.com/media/buildings/arena.webp",
    type: "Commercial",
    color: "#BD00FF",
  },
  {
    id: "22",
    position: [-8.6, 1.3, -1.4],
    rotationX: -70,
    rotationY: 10,
    scale: 3.9,
    iconPosition: 0.6,
    name: "Love Palace",
    image: "https://www.boozedbunnytown.com/media/buildings/love_palace.webp",
    type: "Commercial",
    color: "#BD00FF",
  },
  {
    id: "23",
    position: [7, 1.3, -1.8],
    rotationX: -70,
    rotationY: -10,
    scale: 3.4,
    iconPosition: 0.58,
    name: "Gnome Party House",
    image:
      "https://www.boozedbunnytown.com/media/buildings/gnome_party_house.webp",
    type: "Commercial",
    color: "#BD00FF",
  },
  {
    id: "24",
    position: [5, 2.6, 4.8],
    rotationX: -70,
    rotationY: -20,
    scale: 7.5,
    iconPosition: 0.34,
    name: "Casino Pyramid",
    image:
      "https://www.boozedbunnytown.com/media/buildings/casino_pyramid.webp",
    type: "Commercial",
    color: "#BD00FF",
  },
 /*  {
    id: "25",
    position: [5, 0.8, 7.9],
    rotationY: 160,
    image:
      "https://www.boozedbunnytown.com/media/buildings/ubis_postproduction.webp",
    type: "Commercial",
    color: "#BD00FF",
  },
  {
    id: "26",
    position: [-7, 0.8, -6.2],
    rotationY: 20,
    image:
      "https://www.boozedbunnytown.com/media/buildings/lolas_bunny_house.webp",
    type: "Commercial",
    color: "#BD00FF",
  }, */
    {
    id: "25",
    position: [9.3, 1, -3.3],
    rotationX: -70,
    rotationY: -10,
    scale: 5.5,
    iconPosition: 0.54,
    name: "Stock Exchange",
    image:
      "https://www.boozedbunnytown.com/media/buildings/stock.webp",
    type: "Commercial",
    color: "#BD00FF",
  },
];
