"use client";

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 https://www.boozedbunnytown.com/public/media/models/player.glb -t 
*/

import * as THREE from "three";
import React, { useEffect } from "react"; // useEffect hinzugefügt
import { useGraph } from "@react-three/fiber";
import { useGLTF, useAnimations } from "@react-three/drei";
import { GLTF, SkeletonUtils } from "three-stdlib";

type ActionName =
  | "Backflip_and_Rise"
  | "Drinking"
  | "Fall_Ground"
  | "FreeFalling"
  | "Idle_1"
  | "Idle_2"
  | "Idle_3"
  | "Jump"
  | "Limping_Walk"
  | "Run"
  | "Running"
  | "Sleeping"
  | "Sleeping2"
  | "Staggering"
  | "Stumble_Walk"
  | "Stylish_Walk"
  | "Trippin"
  | "Walk"
  | "Walk_Backwards"
  | "Walking";

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName;
}

type GLTFResult = GLTF & {
  nodes: {
    char1: THREE.SkinnedMesh;
    Hips: THREE.Bone;
  };
  materials: {
    Material_1: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

export function Model({ currentAction = "Idle_1", avatar = "bunny", ...props }: any) {
  const group = React.useRef<THREE.Group>(null);
  const { scene, animations } = useGLTF(`https://www.boozedbunnytown.com/media/models/player_${avatar}.glb`);
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone) as unknown as GLTFResult;
  const { actions } = useAnimations(animations, group);

  // NEU: Dieser Hook kümmert sich um das Abspielen und das weiche Überblenden (Crossfade)
  useEffect(() => {
    const action = actions[currentAction];
    if (action) {
      // Setze die Animation zurück, blende sie in 0.2 Sekunden ein und spiele sie ab
      action.reset().fadeIn(0.2).play();

      // Wenn eine neue Aktion kommt, blende die alte in 0.2 Sekunden sanft aus
      return () => {
        action.fadeOut(0.2);
      };
    }
  }, [currentAction, actions]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" scale={0.01}>
          <primitive object={nodes.Hips} />
        </group>
        <skinnedMesh
          name="char1"
          geometry={nodes.char1.geometry}
          material={materials.Material_1}
          skeleton={nodes.char1.skeleton}
          scale={0.01}
        />
      </group>
    </group>
  );
}

if (typeof window !== "undefined") {
  useGLTF.preload("https://www.boozedbunnytown.com/media/models/player_bunny.glb");
  useGLTF.preload("https://www.boozedbunnytown.com/media/models/player_cowie.glb");
  useGLTF.preload("https://www.boozedbunnytown.com/media/models/player_skunky.glb");
  useGLTF.preload("https://www.boozedbunnytown.com/media/models/player_nutty.glb");
}
